name: 'Notion To JSON/YML File'
description: 'Reads from a Notion Database and auto generates a JSON/YML file'
inputs:
  notion-token:
    description: 'Notion token'
    required: true
  notion-db:
    description: 'Notion database'
    required: true
  output-file:
    description: 'File to output'
    required: true
  output-format:
    description: 'File format to output. Normally deduced from file output extension.'
    required: false
  ignore-columns:
    description: 'If any, ignore the columns specified by name'
    required: false
outputs:
  updated:
    description: 'Whether it was updated or not'
runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: "log-in"
  color: "blue"