name: 'Hello World'
description: 'Reads from a Notion Database and auto generates a file, then creates a PR'
inputs:
  notion-token:
    description: 'Notion token'
    required: true
  notion-db:
    description: 'Notion database'
    required: true
  output-file:
    description: 'File to output'
    required: true
    default: 'notion.json'
outputs:
  updated:
    description: 'Whether it was updated or not'
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: "log-in"
  color: "blue"