on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  notion-to-file:
    runs-on: ubuntu-latest
    name: A job to test the action
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test notion import from DB
        uses: ./ # Uses an action in the root directory
        id: test-notion-import
        with:
          notion-token: ${{ secrets.NOTION_TOKEN }}
          notion-db: ${{ secrets.NOTION_DATABASE }}
          output-file: 'notion.yml'
          output-format: 'json'
      # Use the output from the `hello` step
#      - name: Get the output time
#        run: echo "The time was ${{ steps.hello.outputs.time }}"
